"""TypeScript types generated from the OpenAPI schema and the golden JSON Schemas (plan §4.10).

A small JSON-Schema-to-TypeScript converter for the subset pydantic emits (objects, arrays, enums,
const, anyOf/oneOf, $ref to $defs/components, additionalProperties). Deterministic output.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Mapping

HEADER = "// Generated by `redactor api types` from the OpenAPI schema and schemas/*.json. Do not edit.\n\n"


def _name(ref: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", ref.rsplit("/", 1)[-1])


def ts_type(s: Mapping[str, Any] | bool) -> str:
    if s is True or s == {}:
        return "unknown"
    if s is False:
        return "never"
    if "$ref" in s:
        return _name(s["$ref"])
    if "const" in s:
        return json.dumps(s["const"])
    if "enum" in s:
        return " | ".join(json.dumps(v) for v in s["enum"])
    for key in ("anyOf", "oneOf"):
        if key in s:
            return " | ".join(sorted({ts_type(x) for x in s[key]}, key=lambda t: (t == "null", t)))
    if "allOf" in s and len(s["allOf"]) == 1:
        return ts_type(s["allOf"][0])
    t = s.get("type")
    if isinstance(t, list):
        return " | ".join(ts_type({**s, "type": x}) for x in t)
    if t == "string":
        return "string"
    if t in ("integer", "number"):
        return "number"
    if t == "boolean":
        return "boolean"
    if t == "null":
        return "null"
    if t == "array":
        inner = ts_type(s.get("items", {}))
        return f"({inner})[]" if "|" in inner else f"{inner}[]"
    if t == "object" or "properties" in s:
        props = s.get("properties") or {}
        if not props:
            ap = s.get("additionalProperties", True)
            return f"Record<string, {ts_type(ap) if isinstance(ap, dict) else 'unknown'}>"
        req = set(s.get("required", []))
        fields = []
        for k in props:
            key = k if re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", k) else json.dumps(k)
            fields.append(f"  {key}{'' if k in req else '?'}: {ts_type(props[k])};")
        return "{\n" + "\n".join(fields) + "\n}"
    return "unknown"


def generate(openapi: Mapping[str, Any], json_schemas: Mapping[str, Mapping[str, Any]]) -> str:
    defs: dict[str, Any] = {}
    for name, sch in sorted((openapi.get("components") or {}).get("schemas", {}).items()):
        defs[_name(name)] = sch
    for title, sch in sorted(json_schemas.items()):
        for name, d in (sch.get("$defs") or {}).items():
            defs.setdefault(_name(name), d)
        defs[_name(title)] = {k: v for k, v in sch.items() if k != "$defs"}
    out = [HEADER]
    for name in sorted(defs):
        t = ts_type(defs[name])
        out.append(f"export type {name} = {t};\n\n")
    paths = sorted((openapi.get("paths") or {}).items())
    out.append("export const API_PATHS = [\n")
    for p, ops in paths:
        for m in sorted(ops):
            out.append(f"  {json.dumps(m.upper() + ' ' + p)},\n")
    out.append("] as const;\n")
    return "".join(out)


def write(out_path: Path, openapi: Mapping[str, Any], schemas_dir: Path) -> int:
    schemas = {}
    for p in sorted(schemas_dir.glob("*.json")):
        sch = json.loads(p.read_text(encoding="utf-8"))
        schemas[sch.get("title") or p.stem] = sch
    text = generate(openapi, schemas)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8", newline="\n")
    return text.count("export type")
