"""Philter candidate (plan §11 C1): the pinned `philterd/philter:3.4.1` image (Phileas 3.3.0), run locally.

Isolation: the container runs with `--network none` (only loopback exists inside it), so no document
text can leave it. Our policies, properties and a JDK-stdlib loopback client are bind-mounted read-only;
texts go in base64 over `docker exec` stdin and the `/api/explain` spans come back the same way. TLS is
off because the only listener is loopback inside a network-less container. The container is removed
when the process ends.

Policies (sidecars/philter/policies/, generated by make_policies.py): `default` (every built-in filter
that works offline) and `au_extended` (plus Australian identifier patterns), run as separate
experiments. Philter's `person` filter needs the separate PhEye model service, which is not in the
pinned image, so PERSON comes only from the first-name / surname / physician-name dictionaries.
"""

from __future__ import annotations

import atexit
import base64
import json
import os
import subprocess
import time
from typing import Any, Mapping, Sequence

from ...core.canonical import sha256_file, sha256_obj
from ..base import register_detector
from .common import AdapterBase, Raw, repo_path

IMAGE = "philterd/philter:3.4.1"
IMAGE_ID = "sha256:9fabd3cb5cd0013a11c8628d7d0a62a3017161c505450c826725aee82e29d780"
_RUNNING: dict[str, str] = {}


class PhilterError(RuntimeError):
    pass


def _cleanup() -> None:
    for name in list(_RUNNING.values()):
        subprocess.run(["docker", "rm", "-f", name], capture_output=True)


atexit.register(_cleanup)


class PhilterAdapter(AdapterBase):
    name = "philter"
    version = "0.1.0"
    label_map_name = "philter"

    def __init__(self, config: Mapping[str, Any] | None = None):
        cfg = {"policy": "default", **dict(config or {})}
        if cfg["policy"] not in ("default", "au_extended"):
            raise ValueError("philter policy must be default or au_extended")
        super().__init__(cfg)
        self.name = "philter" if cfg["policy"] == "default" else "philter_au"
        self.restarts = 0

    def _sidecar_files(self) -> dict[str, str]:
        d = repo_path("sidecars", "philter")
        return {p.name: sha256_file(p)[:16] for p in sorted([d / "philter.properties", d / "client" / "Explain.java",
                                                             *(d / "policies").glob("*.json")])}

    def engine_fingerprint(self) -> dict[str, Any]:
        return {"image": IMAGE, "image_id": IMAGE_ID, "files": self._sidecar_files()}

    def _container(self) -> str:
        key = sha256_obj(self.engine_fingerprint())[:12]
        if key in _RUNNING:
            return _RUNNING[key]
        got = subprocess.run(["docker", "image", "inspect", IMAGE, "--format", "{{.Id}}"], capture_output=True, text=True)
        if got.returncode != 0 or got.stdout.strip() != IMAGE_ID:
            raise PhilterError("pinned Philter image missing or different (docker pull philterd/philter:3.4.1)")
        d = repo_path("sidecars", "philter")
        name = f"redactor-philter-{key}-{os.getpid()}"   # per process: fresh-process determinism runs coexist
        subprocess.run(["docker", "rm", "-f", name], capture_output=True)
        cmd = ["docker", "run", "-d", "--rm", "--name", name, "--network", "none", "-e", "OMP_THREAD_LIMIT=1",
               "--mount", f"type=bind,source={d / 'policies'},target=/opt/philter/policies,readonly",
               "--mount", f"type=bind,source={d / 'philter.properties'},target=/opt/philter/philter.properties,readonly",
               "--mount", f"type=bind,source={d / 'client'},target=/client,readonly", IMAGE]
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            raise PhilterError(f"could not start the Philter container (exit {r.returncode})")
        _RUNNING[key] = name
        for _ in range(90):
            s = subprocess.run(["docker", "exec", name, "java", "/client/Explain.java", "status"], capture_output=True, text=True)
            if s.returncode == 0 and s.stdout.startswith("200"):
                return name
            time.sleep(2)
        raise PhilterError("Philter did not become ready")

    MAX_RESTARTS = 5

    def _restart(self) -> None:
        key = sha256_obj(self.engine_fingerprint())[:12]
        name = _RUNNING.pop(key, None)
        if name:
            subprocess.run(["docker", "rm", "-f", name], capture_output=True)
        self.restarts += 1

    def _explain(self, texts: Sequence[str]) -> tuple[list[str], str]:
        """Runs the loopback client; returns the result lines delivered so far and a text-free failure note."""
        import re
        name = self._container()
        payload = "".join(base64.b64encode(t.encode("utf-8")).decode("ascii") + "\n" for t in texts)
        r = subprocess.run(["docker", "exec", "-i", name, "java", "/client/Explain.java", "explain", self.config["policy"]],
                           input=payload, capture_output=True, text=True, encoding="utf-8")
        lines = [ln for ln in r.stdout.splitlines() if ln.strip()]
        if r.returncode == 0:
            return lines, ""
        code = re.findall(r"explain failed: HTTP (\d+)", r.stderr or "")        # the client prints only this line
        exc = sorted(set(re.findall(r"(java\.[\w.]+(?:Exception|Error))", r.stderr or "")))   # class names only
        st = subprocess.run(["docker", "inspect", name, "--format", "{{.State.Running}} {{.State.OOMKilled}} {{.State.ExitCode}}"],
                            capture_output=True, text=True).stdout.strip()
        return lines, (f"exit {r.returncode}, HTTP {code[0] if code else 'n/a'}, client {exc or 'n/a'}, "
                       f"container running/oom/exit {st or 'gone'}")

    def analyze(self, texts: Sequence[str]) -> list[list[Raw]]:
        lines: list[str] = []
        restarts = 0
        while len(lines) < len(texts):
            got, failure = self._explain(texts[len(lines):])
            lines += got
            if failure:
                # Philter 3.4.1 occasionally hangs or answers 500 after many requests, while every page succeeds
                # on a fresh service; a restart and resume gives the same deterministic answers. 4xx is a real error.
                if "HTTP 4" in failure:
                    raise PhilterError(f"Philter explain failed ({failure})")
                if restarts >= self.MAX_RESTARTS:
                    raise PhilterError(f"Philter kept failing after {restarts} restarts ({failure})")
                restarts += 1
                self._restart()
        if len(lines) != len(texts):
            raise PhilterError("Philter returned a different number of results")
        out = []
        for t, ln in zip(texts, lines):
            body = json.loads(base64.b64decode(ln).decode("utf-8"))
            spans = (body.get("explanation") or {}).get("identifiedSpans") or []
            out.append([Raw(int(s["characterStart"]), int(s["characterEnd"]), str(s.get("filterType", "OTHER")),
                            None if s.get("confidence") is None else round(float(s["confidence"]), 4))
                        for s in spans if 0 <= int(s["characterStart"]) < int(s["characterEnd"]) <= len(t)])
        return out

    def stats(self) -> dict[str, Any]:
        return {**super().stats(), "container_restarts": self.restarts}


@register_detector("philter")
def _make(config: Mapping[str, Any]) -> PhilterAdapter:
    return PhilterAdapter({**dict(config or {}), "policy": (config or {}).get("policy", "default")})


@register_detector("philter_au")
def _make_au(config: Mapping[str, Any]) -> PhilterAdapter:
    return PhilterAdapter({**dict(config or {}), "policy": "au_extended"})
