// Generated by `redactor api types` from the OpenAPI schema and schemas/*.json. Do not edit.

export type AnnotationSet = {
  annotator: "A1" | "A2" | "claude_silver" | "adjudicated";
  coverage?: Coverage;
  document_id: string;
  document_sha256: string;
  entities?: Entity[];
  guidelines_version: string;
  ignore_regions?: IgnoreRegion[];
  mode: "blind" | "candidates_shown" | "silver" | "adjudicated";
  pass?: number;
  policy_ref: string;
  revision?: number;
  schema?: "golden.annotation_set";
  schema_version?: string;
  silver?: SilverInfo | null;
};

export type Body_promote_promote__doc__post = {
  source: string;
  verified_by: string;
};

export type Box = {
  x0: number;
  x1: number;
  y0: number;
  y1: number;
};

export type CanonicalRegistry = {
  annotator?: "A1" | "A2" | "claude_silver" | "adjudicated";
  entities?: RegistryEntity[];
  matter_id: string;
  schema?: "golden.canonical_registry";
  schema_version?: string;
  silver?: SilverInfo | null;
};

export type Classification = {
  classifier: string;
  content_kind: "born_digital" | "scanned" | "vector_outlined" | "hybrid" | "blank" | "unknown";
  human_verified?: boolean;
  invisible_ocr_layer?: boolean;
  ocr_required: boolean;
  ocr_scope: "none" | "raster_regions" | "full_page";
  text_layer: "usable" | "present_unusable" | "absent";
};

export type Coverage = {
  fields_complete?: ("filename" | "pdf.title" | "pdf.author" | "pdf.subject" | "pdf.keywords" | "xmp")[];
  pages_complete?: number[];
  pages_verified?: number[];
  types_complete?: ("PERSON" | "ORGANIZATION" | "ADDRESS" | "EMAIL" | "PHONE" | "URL" | "LOCATION" | "CLAIM_NUMBER" | "COURT_FILE_NUMBER" | "POLICY_NUMBER" | "TFN" | "ABN" | "ACN" | "PASSPORT" | "DRIVER_LICENCE" | "VEHICLE_REGISTRATION" | "CENTRELINK_CRN" | "ACCOUNT_NUMBER" | "MEDICARE" | "PROVIDER_NUMBER" | "AHPRA_REGISTRATION" | "IHI" | "MEDICAL_RECORD_NUMBER" | "DVA_NUMBER" | "DATE" | "AGE" | "DATE_OF_BIRTH" | "GENDER" | "NATIONALITY" | "SIGNATURE" | "PHOTO" | "OTHER")[];
};

export type DecisionBody = {
  item_id: string;
  decision: string;
  reason?: string | null;
  payload?: Record<string, unknown> | null;
};

export type DocGate = {
  leak_scan: string;
  status: string;
};

export type DocumentMetadata = {
  document_id: string;
  document_type: string;
  matter_id: string;
  original_filename: string;
  page_count: number;
  pages: PageMeta[];
  pdf: PdfInfo;
  schema?: "golden.document_metadata";
  schema_version?: string;
  sha256: string;
  size_bytes: number;
  source_path: string;
  split: "dev" | "test" | "intake";
};

export type EditEntry = {
  action: string;
  canonical_id: string | null;
  edit_id: string;
  entity_type: string;
  field?: string | null;
  new_end: number;
  new_start: number;
  page: number | null;
  rule_id: string;
  span_id: string | null;
  strategy: string | null;
};

export type Entity = {
  action: "KEEP" | "SYNTHETIC" | "REDACT" | "REVIEW";
  action_source?: "policy" | "override";
  attributes?: Record<string, unknown>;
  canonical_id?: string | null;
  certainty?: "certain" | "probable" | "uncertain";
  entity_id: string;
  entity_type: "PERSON" | "ORGANIZATION" | "ADDRESS" | "EMAIL" | "PHONE" | "URL" | "LOCATION" | "CLAIM_NUMBER" | "COURT_FILE_NUMBER" | "POLICY_NUMBER" | "TFN" | "ABN" | "ACN" | "PASSPORT" | "DRIVER_LICENCE" | "VEHICLE_REGISTRATION" | "CENTRELINK_CRN" | "ACCOUNT_NUMBER" | "MEDICARE" | "PROVIDER_NUMBER" | "AHPRA_REGISTRATION" | "IHI" | "MEDICAL_RECORD_NUMBER" | "DVA_NUMBER" | "DATE" | "AGE" | "DATE_OF_BIRTH" | "GENDER" | "NATIONALITY" | "SIGNATURE" | "PHOTO" | "OTHER";
  field?: "filename" | "pdf.title" | "pdf.author" | "pdf.subject" | "pdf.keywords" | "xmp" | null;
  flags?: ("handwritten" | "ocr_degraded" | "split_line" | "split_page" | "partially_illegible" | "quasi_identifier")[];
  notes?: string;
  override_reason?: string | null;
  page?: number | null;
  provenance: Provenance;
  regions?: Region[];
  role?: string | null;
  text?: string | null;
  text_anchor?: TextAnchor | null;
};

export type ExportBody = {
  formats?: string[];
};

export type ExtractionInfo = {
  engine: string;
  engine_version: string;
  method: "text_layer" | "ocr" | "hybrid";
  model_sha256?: string | null;
  render?: RenderInfo | null;
  text_source_id: string;
};

export type HTTPValidationError = {
  detail?: ValidationError[];
};

export type IgnoreRegion = {
  page: number;
  reason: string;
  regions: Region[];
};

export type Manifest = {
  dataset_version?: string;
  documents?: ManifestDocument[];
  exceptions?: string[];
  files?: Record<string, string>;
  schema?: "golden.manifest";
  schema_version?: string;
  verification_sample?: VerificationSample | null;
};

export type ManifestDocument = {
  document_id: string;
  matter_id: string;
  registered_order: number;
  sha256: string;
  size_bytes: number;
  source_name_sha256: string;
  split: "dev" | "test" | "intake";
};

export type Page = {
  content_kind: string;
  gate: PageGate;
  page: number;
  spans: Span[];
  text: string;
  text_source_id: string;
};

export type PageClassBody = {
  content_kind: string;
  verified_by: string;
};

export type PageGate = {
  reasons: string[];
  status: string;
};

export type PageMeta = {
  classification: Classification;
  extraction?: ExtractionInfo | null;
  height_pt: number;
  page: number;
  rotation: number;
  signals: Signals;
  width_pt: number;
};

export type PageTranscript = {
  document_id: string;
  lines: TranscriptLine[];
  page: number;
  reading_order?: "top_down_left_right";
  schema?: "golden.page_transcript";
  schema_version?: string;
  seeded_from: string;
  verified_by?: string | null;
};

export type PdfInfo = {
  annotations: number;
  creator?: string | null;
  embedded_files: number;
  encrypted: boolean;
  form_fields: number;
  metadata_fields_present: string[];
  producer: string | null;
  version: string | null;
};

export type Provenance = {
  adjudication?: "agreed" | "took_A1" | "took_A2" | "verified_silver" | "merged" | "added" | null;
  annotator: "A1" | "A2" | "claude_silver" | "adjudicated";
  origin: "manual" | "preannotation_accepted" | "preannotation_edited" | "audit_added" | "silver";
  pass: number;
  verified_by?: string | null;
  verified_date?: string | null;
};

export type PseudonymizedDocument = {
  document_id: string;
  edit_log: EditEntry[];
  fields: Record<string, string>;
  gate: DocGate;
  matter_id: string;
  output_sha256: string;
  pages: Page[];
  pipeline: Record<string, unknown>;
  schema: "redaction.pseudonymized_document";
  schema_version: string;
  source_sha256: string;
};

export type Region = {
  x0: number;
  x1: number;
  y0: number;
  y1: number;
};

export type RegistryBody = {
  base_sha: string;
  registry: Record<string, unknown>;
};

export type RegistryEntity = {
  canonical_id: string;
  date_of_birth?: string | null;
  entity_type: "PERSON" | "ORGANIZATION" | "ADDRESS" | "EMAIL" | "PHONE" | "URL" | "LOCATION" | "CLAIM_NUMBER" | "COURT_FILE_NUMBER" | "POLICY_NUMBER" | "TFN" | "ABN" | "ACN" | "PASSPORT" | "DRIVER_LICENCE" | "VEHICLE_REGISTRATION" | "CENTRELINK_CRN" | "ACCOUNT_NUMBER" | "MEDICARE" | "PROVIDER_NUMBER" | "AHPRA_REGISTRATION" | "IHI" | "MEDICAL_RECORD_NUMBER" | "DVA_NUMBER" | "DATE" | "AGE" | "DATE_OF_BIRTH" | "GENDER" | "NATIONALITY" | "SIGNATURE" | "PHOTO" | "OTHER";
  gender?: "female" | "male" | "non_binary" | "unknown" | null;
  gender_evidence?: string | null;
  label?: string;
  notes?: string;
  role?: string | null;
};

export type ReidentifyBody = {
  text: string;
};

export type RenderInfo = {
  dpi: number;
  engine: string;
  mode?: "gray" | "rgb";
  version: string;
};

export type SaveBody = {
  base_revision: number;
  annotation: Record<string, unknown>;
};

export type Signals = {
  alnum_ratio: number | null;
  bad_char_ratio?: number | null;
  image_count: number;
  image_coverage: number;
  image_dpi: number[];
  invisible_text_chars: number;
  largest_image_fraction?: number;
  small_filled_paths?: number;
  vector_paths: number;
  visible_text_chars: number;
};

export type SilverInfo = {
  exception?: "EX-001";
  guidelines_version: string;
  input_sha256s: Record<string, string>;
  model_id: string;
  prompt_sha256: string;
  run_date: string;
};

export type Span = {
  action: "SYNTHETIC" | "REDACT" | "REVIEW" | "KEEP";
  bboxes: Box[];
  canonical_id: string | null;
  end: number;
  entity_type: string;
  span_id: string;
  start: number;
};

export type TextAnchor = {
  end: number;
  start: number;
  text_source_id: string;
};

export type TranscriptLine = {
  bbox: Region;
  text: string;
};

export type ValidationError = {
  loc: (number | string)[];
  msg: string;
  type: string;
};

export type VerificationSample = {
  drawn_before_verification?: boolean;
  pages?: Record<string, number[]>;
  seed: string;
};

export const API_PATHS = [
  "POST /annotations/A1/{doc}/start-from-silver",
  "GET /annotations/{annotator}/{doc}",
  "PUT /annotations/{annotator}/{doc}",
  "POST /annotations/{annotator}/{doc}/submit",
  "GET /candidates/{doc}",
  "GET /documents",
  "GET /documents/{doc}",
  "GET /documents/{doc}/fields",
  "GET /documents/{doc}/pages/{page}/image",
  "GET /documents/{doc}/pages/{page}/words",
  "GET /experiments",
  "POST /experiments/{name}/launch",
  "POST /export/{matter}",
  "GET /export/{matter}/status",
  "GET /extractions/{doc}",
  "GET /extractions/{doc}/pages/{page}",
  "GET /health",
  "GET /iaa/{doc}",
  "GET /intake",
  "POST /intake/{matter}",
  "GET /jobs/{job_id}",
  "GET /page-classes/{doc}",
  "PUT /page-classes/{doc}/{page}",
  "GET /preview/{matter}/{doc}",
  "GET /preview/{matter}/{doc}/{page}/image",
  "POST /promote/{doc}",
  "GET /registry/{annotator}",
  "PUT /registry/{annotator}",
  "POST /reidentify/{matter}",
  "GET /review/{matter}",
  "POST /review/{matter}/decisions",
  "GET /review/{matter}/page/{doc}/{page}",
  "GET /review/{matter}/rerun",
  "POST /review/{matter}/rerun",
  "GET /runs",
  "GET /runs/{run_id}",
  "GET /runs/{run_id}/private/mentions",
  "GET /runs/{run_id}/private/overlay/{doc}/{page}",
  "GET /runs/{run_id}/private/predictions/{doc}",
  "GET /runs/{run_id}/report",
  "GET /taxonomy",
] as const;
